/**
 * Created by dionis on 04/12/14.
 */
var keyMirror = require('react/lib/keyMirror');
module.exports = keyMirror({
    SOCIAL_NET_RENTER_POSTS_FOUND: null,
    SOCIAL_NET_RENTER_POSTS_RESET_SEARCH: null,
    SOCIAL_NET_RENTER_POSTS_SAVE_SEARCH_TEXT: null,
    SOCIAL_NET_RENTER_POSTS_SAVE_SEARCH_WITH_SUBWAY: null,

    SOCIAL_NET_LESSOR_POSTS_FOUND: null,
    SOCIAL_NET_LESSOR_POSTS_RESET_SEARCH: null,
    SOCIAL_NET_LESSOR_POSTS_SAVE_SEARCH_TEXT: null,
    SOCIAL_NET_LESSOR_POSTS_SAVE_SEARCH_WITH_SUBWAY: null,

    //FB
    SOCIAL_NET_FB_POSTS_FOUND: null,
    SOCIAL_NET_FB_POSTS_RESET_SEARCH: null,
    SOCIAL_NET_FB_POSTS_SAVE_SEARCH_TEXT: null,
    SOCIAL_NET_FB_POSTS_SAVE_SEARCH_WITH_SUBWAY: null,
    SOCIAL_NET_FB_POSTS_SAVE_SEARCH_TYPE: null,
    SOCIAL_NET_FB_POSTS_SAVE_SEARCH_ROOMS: null
});