DROP TABLE IF EXISTS feedback;
CREATE TABLE feedback (
  id         BIGINT NOT NULL PRIMARY KEY,
  creator_id BIGINT,
  text       TEXT,
  created_dt TIMESTAMP WITH TIME ZONE,
  updated_dt TIMESTAMP WITH TIME ZONE
);

DROP SEQUENCE IF EXISTS feedback_id_seq;
CREATE SEQUENCE feedback_id_seq
INCREMENT 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 1
CACHE 1;