export const APARTMENT_LOAD_DETAILS = 'APARTMENT_LOAD_DETAILS'
export const APARTMENT_SAVE_DETAILS = 'APARTMENT_SAVE_DETAILS'

export const APARTMENT_LIST_CLEAR_LOADING = 'APARTMENT_LIST_CLEAR_LOADING'
export const APARTMENT_SEARCH_INPUT_GEO_ERROR = 'APARTMENT_SEARCH_INPUT_GEO_ERROR'
export const APARTMENT_LIST_NEXT_PAGE_LOADING = 'APARTMENT_LIST_NEXT_PAGE_LOADING'
export const APARTMENT_LOAD_LIST_PART = 'APARTMENT_LOAD_LIST_PART'
export const APARTMENT_ERROR_LOADING = 'APARTMENT_ERROR_LOADING'
