export const APARTMENT_LOAD_DETAILS = 'APARTMENT_LOAD_DETAILS'
export const APARTMENT_SAVE_DETAILS = 'APARTMENT_SAVE_DETAILS'

export const APARTMENT_LIST_CLEAR_LOADING = 'APARTMENT_LIST_CLEAR_LOADING'
export const APARTMENT_LOAD_LIST_PART = 'APARTMENT_LOAD_LIST_PART'
